version: '3'

services:

    nginx:
        build: nginx
        image: ${REGISTRY_URL}${REPOSITORY_NAME}:${PROJECT_NAME}__frontend--latest
        depends_on:
            - php
        ports:
            - 80:80

    php:
        build: php
        image: ${REGISTRY_URL}${REPOSITORY_NAME}:${PROJECT_NAME}__php--latest
        working_dir: /var/www/${HOST}